AppName: "backend"
HttpPort: ":8080"
LogLevel: "debug"
DatabaseUrl: "host=localhost dbname=restapi_dev sslmode=disable"
RulesPath: "./data/rules/"
ExamsPath: "./data/exams/"
DBName: "my_db"
DBHost: "localhost"
DBPort: "5432"
DBUser: "postgres"
DBPassword: "postgres"