AppName: "backend"
HttpPort: ":8080"
LogLevel: "debug"
RulesPath: "./data/rules/"
ExamsPath: "./data/exams/"
DBName: "mydb_hm1w"
DBHost: "dpg-cei9mhqrrk07uhbmjof0-a.frankfurt-postgres.render.com"
DBPort: "5432"
DBUser: "mydb"
DBPassword: "LL9bjuiH5A7qx8YVcpl8X7R7yVqWrLkO"
